name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  provider: ^6.1.5
  firebase_core: ^4.0.0
  firebase_ai: ^3.1.0
  go_router: ^16.1.0
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  url_launcher: ^6.3.2
  google_mlkit_translation: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
