import '../models/statute.dart';

class LegalLibraryService {
  static final List<Statute> _statutes = [
    // Existing 75 Statutes
    Statute(number: '782.04', title: 'Murder'),
    Statute(number: '782.07', title: 'Manslaughter'),
    Statute(number: '784.011', title: 'Assault'),
    Statute(number: '784.021', title: 'Aggravated Assault'),
    Statute(number: '784.03', title: 'Battery'),
    Statute(number: '784.045', title: 'Aggravated Battery'),
    Statute(number: '784.041', title: 'Felony Battery'),
    Statute(number: '784.07', title: 'Assault or Battery on LEO'),
    Statute(number: '787.01', title: 'Kidnapping'),
    Statute(number: '787.02', title: 'False Imprisonment'),
    Statute(number: '790.01', title: 'Carrying a Concealed Weapon'),
    Statute(number: '790.07', title: 'Carrying a Concealed Firearm'),
    Statute(number: '790.15', title: 'Discharging a Firearm in Public'),
    Statute(number: '790.23', title: 'Possession of Firearm by Felon'),
    Statute(number: '794.011', title: 'Sexual Battery'),
    Statute(number: '800.04', title: 'Lewd or Lascivious Molestation'),
    Statute(number: '806.01', title: 'Arson'),
    Statute(number: '806.13', title: 'Criminal Mischief'),
    Statute(number: '810.02', title: 'Burglary'),
    Statute(number: '810.08', title: 'Trespass in Structure or Conveyance'),
    Statute(number: '810.09', title: 'Trespass on Property Other Than Structure'),
    Statute(number: '812.014', title: 'Theft (Petit and Grand)'),
    Statute(number: '812.015', title: 'Retail Theft'),
    Statute(number: '812.019', title: 'Dealing in Stolen Property'),
    Statute(number: '812.13', title: 'Robbery'),
    Statute(number: '812.131', title: 'Robbery by Sudden Snatching'),
    Statute(number: '812.133', title: 'Carjacking'),
    Statute(number: '817.034', title: 'Florida Communications Fraud Act'),
    Statute(number: '817.568', title: 'Fraudulent Use of Personal ID'),
    Statute(number: '828.12', title: 'Cruelty to Animals'),
    Statute(number: '831.01', title: 'Forgery'),
    Statute(number: '831.02', title: 'Uttering a Forged Instrument'),
    Statute(number: '832.05', title: 'Worthless Checks'),
    Statute(number: '837.02', title: 'Perjury'),
    Statute(number: '837.05', title: 'False Reports to Law Enforcement'),
    Statute(number: '843.01', title: 'Resisting Officer with Violence'),
    Statute(number: '843.02', title: 'Resisting Officer without Violence'),
    Statute(number: '843.15', title: 'Failure to Appear'),
    Statute(number: '856.011', title: 'Disorderly Intoxication'),
    Statute(number: '856.021', title: 'Loitering or Prowling'),
    Statute(number: '870.01', title: 'Affrays and Riots'),
    Statute(number: '877.03', title: 'Disorderly Conduct'),
    Statute(number: '893.13', title: 'Possession of a Controlled Substance'),
    Statute(number: '893.135', title: 'Trafficking in Controlled Substances'),
    Statute(number: '901.15', title: 'Lawful Arrests Without a Warrant'),
    Statute(number: '916.19', title: 'Competency to Proceed'),
    Statute(number: '943.05', title: 'Criminal History Records'),
    Statute(number: '316.061', title: 'Crashes involving damage to vehicle or property'),
    Statute(number: '316.062', title: 'Duty to give information and render aid'),
    Statute(number: '316.066', title: 'Written reports of crashes'),
    Statute(number: '316.192', title: 'Reckless Driving'),
    Statute(number: '316.193', title: 'Driving Under the Influence (DUI)'),
    Statute(number: '316.1935', title: 'Fleeing or Eluding a LEO'),
    Statute(number: '316.614', title: 'Safety Belt Usage'),
    Statute(number: '320.02', title: 'Registration required'),
    Statute(number: '322.03', title: 'Drivers must be licensed'),
    Statute(number: '322.15', title: 'License to be carried and exhibited'),
    Statute(number: '322.34', title: 'Driving while license suspended/revoked'),
    Statute(number: '324.022', title: 'Proof of financial responsibility'),
    Statute(number: '316.074', title: 'Obedience to traffic control devices'),
    Statute(number: '316.075', title: 'Traffic control signal devices'),
    Statute(number: '316.089', title: 'Driving on roadways laned for traffic'),
    Statute(number: '316.126', title: 'Operation of vehicles on approach of emergency vehicles'),
    Statute(number: '316.130', title: 'Pedestrian obedience to traffic control devices'),
    Statute(number: '316.2065', title: 'Bicycle regulations'),
    Statute(number: '316.303', title: 'Unlawful use of a wireless communications device'),
    Statute(number: '775.085', title: 'Hate Crimes (Enhanced Penalties)'),
    Statute(number: '776.012', title: 'Use of Force in Defense of Person'),
    Statute(number: '776.013', title: 'Home Protection; Use of Deadly Force'),
    Statute(number: '776.031', title: 'Use of Force in Defense of Property'),
    Statute(number: '776.051', title: 'Use of Force by LEO'),
    Statute(number: '776.085', title: 'Excusable Homicide'),
    Statute(number: '784.048', title: 'Stalking'),
    Statute(number: '784.046', title: 'Action by victim of repeat violence'),

    // New 75 Statutes
    Statute(number: '90.502', title: 'Lawyer-client privilege'),
    Statute(number: '90.504', title: 'Husband-wife privilege'),
    Statute(number: '90.802', title: 'Hearsay rule'),
    Statute(number: '90.803', title: 'Hearsay exceptions; availability of declarant immaterial'),
    Statute(number: '90.804', title: 'Hearsay exceptions; declarant unavailable'),
    Statute(number: '92.54', title: 'Chain of custody'),
    Statute(number: '381.004', title: 'HIV testing'),
    Statute(number: '394.463', title: 'Involuntary examination (Baker Act)'),
    Statute(number: '397.675', title: 'Involuntary substance abuse assessment (Marchman Act)'),
    Statute(number: '401.445', title: 'Emergency medical services; consent'),
    Statute(number: '741.28', title: 'Domestic Violence; definitions'),
    Statute(number: '741.29', title: 'Domestic Violence; mandatory arrest'),
    Statute(number: '741.30', title: 'Injunction for protection against domestic violence'),
    Statute(number: '768.28', title: 'Sovereign immunity'),
    Statute(number: '775.021', title: 'Rules of construction'),
    Statute(number: '775.051', title: 'Double jeopardy'),
    Statute(number: '775.082', title: 'Penalties; felonies and misdemeanors'),
    Statute(number: '775.084', title: 'Habitual felony offenders'),
    Statute(number: '775.087', title: '10-20-Life Rule'),
    Statute(number: '777.011', title: 'Principal in first degree'),
    Statute(number: '777.03', title: 'Accessory after the fact'),
    Statute(number: '777.04', title: 'Attempt, solicitation, and conspiracy'),
    Statute(number: '817.234', title: 'False and fraudulent insurance claims'),
    Statute(number: '817.49', title: 'Sale of used motor vehicle goods'),
    Statute(number: '817.60', title: 'Credit card fraud'),
    Statute(number: '827.03', title: 'Child abuse'),
    Statute(number: '827.04', title: 'Child neglect'),
    Statute(number: '838.015', title: 'Bribery'),
    Statute(number: '838.022', title: 'Official misconduct'),
    Statute(number: '839.25', title: 'Tampering with witnesses, victims, or informants'),
    Statute(number: '847.011', title: 'Prohibition of certain acts in connection with obscenity'),
    Statute(number: '849.09', title: 'Lottery'),
    Statute(number: '849.25', title: 'Gambling'),
    Statute(number: '872.02', title: 'Abuse of a dead human body'),
    Statute(number: '874.03', title: 'Criminal gang activity'),
    Statute(number: '876.01', title: 'Treason'),
    Statute(number: '901.01', title: 'Judicial officers'),
    Statute(number: '901.21', title: 'Search of person arrested'),
    Statute(number: '903.03', title: 'Bail'),
    Statute(number: '905.27', title: 'Grand jury testimony'),
    Statute(number: '914.15', title: 'Immunity from prosecution'),
    Statute(number: '918.13', title: 'Tampering with or fabricating physical evidence'),
    Statute(number: '921.0022', title: 'Criminal Punishment Code'),
    Statute(number: '925.035', title: 'Right to counsel'),
    Statute(number: '933.02', title: 'Search warrants'),
    Statute(number: '934.03', title: 'Interception of wire, oral, or electronic communications'),
    Statute(number: '948.06', title: 'Violation of probation or community control'),
    Statute(number: '951.22', title: 'Contraband in county detention facilities'),
    Statute(number: '960.29', title: 'Victim and witness protection'),
    Statute(number: '985.03', title: 'Juvenile definitions'),
    Statute(number: '985.101', title: 'Taking a child into custody'),
    Statute(number: '985.207', title: 'Detention of juvenile'),
    Statute(number: '316.155', title: 'When signal required'),
    Statute(number: '316.172', title: 'Following too closely'),
    Statute(number: '316.183', title: 'Unlawful speed'),
    Statute(number: '316.187', title: 'Establishment of state speed zones'),
    Statute(number: '316.2045', title: 'Stopping, standing, or parking prohibited in specified places'),
    Statute(number: '316.221', title: 'Taillamps'),
    Statute(number: '316.224', title: 'Color of clearance lamps, identification lamps, etc.'),
    Statute(number: '316.271', title: 'Horns and warning devices'),
    Statute(number: '316.2953', title: 'Side windows; restrictions on sunscreening material'),
    Statute(number: '320.0605', title: 'Certificate of registration; possession required'),
    Statute(number: '320.07', title: 'Expiration of registration'),
    Statute(number: '322.16', title: 'Change of address or name'),
    Statute(number: '322.212', title: 'Unlawful use of license'),
    Statute(number: '509.143', title: 'Trespass upon grounds of a public lodging establishment'),
    Statute(number: '562.11', title: 'Selling, giving, or serving alcoholic beverages to person under age 21'),
    Statute(number: '562.111', title: 'Possession of alcoholic beverages by person under age 21'),
    Statute(number: '790.053', title: 'Open carrying of weapons'),
    Statute(number: '790.17', title: 'Furnishing weapons to minors'),
    Statute(number: '810.06', title: 'Possession of burglary tools'),
    Statute(number: '812.022', title: 'Evidence of theft or shoplifting'),
    Statute(number: '843.06', title: 'Neglect or refusal to aid peace officer'),
  ];

  List<Statute> getStatutes() {
    return _statutes;
  }
}
